7. Реализовал хранение данных в БД
EvgeniyKononov/java-filmorate pull request #9
Opened 2022-12-28 18:52 UTC by EvgeniyKononov

2022-12-28 20:11 UTC, db-exp requested changes

2022-12-28 20:11 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/model/film/Film.java
> +    ;
лишнее

2022-12-28 20:11 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/model/film/MPA.java
> +    private String name;
давай добавим валидацию - Size, NotNull итп

2022-12-28 20:11 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/model/user/User.java
> +    public User() {
пустой конструктор лучше удалить

2022-12-28 20:11 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/model/user/User.java
>      private String name;
Давай добавим валидацию на name - Size, NotNull итп

2022-12-28 20:11 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
>      @Autowired
Можно не писать явно Autowired

2022-12-28 20:11 UTC, db-exp commented on README.md
>  ![ER-диаграмма](Filmorate.jpg)
схема не запушилась

2022-12-28 20:11 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
>      @Autowired
можно не писать явно Autowired

2022-12-28 20:11 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +public class FilmDbStorage implements FilmStorage {
а вот тут лучше явно прописать Qualifier, чтобы не запутаться

2022-12-28 20:11 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            //  checkMPA(film.getMpa().getId());
лучше удалять ненужный код

2022-12-28 20:11 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +public class UserDbStorage implements UserStorage {
тут лучше явно прописать Qualifier

2022-12-28 20:11 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +    private HashMap<Long, Boolean> getFriends(Long id) {
лучше вместо HashMap, ArrayList использовать в сигнатурах методов интерфейсы Map, List - это дает гибкость реализации

2022-12-28 20:11 UTC, db-exp commented on src/main/resources/data.sql
> +--INSERT INTO USERS (EMAIL, LOGIN, NAME, BIRTHDAY) VALUES ('test@test.ru', 'test', 'testName', CAST('1986-12-01' as date));
Давай вернем и используем в тестах?

2022-12-28 20:11 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public Film find(Long id) {
лучше назвать findById, чтобы метод отражал суть

2022-12-28 20:11 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +    public User find(Long id) {
лучше назвать findById, чтобы метод отражал суть

2022-12-28 20:11 UTC, db-exp commented on src/test/java/ru/yandex/practicum/filmorate/storage/film/UsersDbStorageTest.java
> +    private final UserDbStorage userStorage;
какая реализация сюда попадает?
Давай явно обозначим с помощью Qualifier реализацию с БД

2022-12-29 05:24 UTC, EvgeniyKononov commented on src/main/resources/data.sql
> +--INSERT INTO USERS (EMAIL, LOGIN, NAME, BIRTHDAY) VALUES ('test@test.ru', 'test', 'testName', CAST('1986-12-01' as date));
Если это раскомментить, то фэйлятся Postman тесты, так как в БД будет то, чего они не ожидают увидеть. Удалил совсем, что бы глаза не мозолило.

2022-12-29 16:53 UTC, EvgeniyKononov commented on src/main/java/ru/yandex/practicum/filmorate/model/user/User.java
> +    public User() {
без пустого конструктора, выдаёт ошибку ниже при создании пользователя. Причём я даже продебажить не могу, так как запрос не доходит даже до контроллера.  Тут как раз написано, что решение данной проблемы - это конструктор по умолчанию.
https://www.baeldung.com/jackson-exception
Оставил конструктор через аннтоцию @NoArgsConstructor.

"error": "Type definition error: [simple type, class ru.yandex.practicum.filmorate.model.user.User]; nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `ru.yandex.practicum.filmorate.model.user.User` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)\n at [Source: (org.springframework.util.StreamUtils$NonClosingInputStream); line: 2, column: 3]"

2022-12-29 17:09 UTC, EvgeniyKononov commented on README.md
>  ![ER-диаграмма](Filmorate.jpg)
в описании проекта картинка отображается нормально. Всё делал по инструкции. Не могу понять, почему при PR она не отображается
![изображение](https://user-images.githubusercontent.com/108692051/209986138-73975ff9-1bb1-43b2-9a5d-a9db383e282b.png)

2022-12-29 17:55 UTC, db-exp approved these changes

2022-12-29 18:04 UTC, merged